sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t clevins/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true clevins/docker-react npm run test